config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'designs#index'

  resources :designs
  resources :designs do
    collection do
      post  '/search',  to: 'designs#search'
      get  '/search',  to: 'designs#search'
    end
  end

  resources :users
  resources :users, only: :show
  post '/designs/new', to: 'designs#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations

  validates :title, presence: true
  validates :file_name, presence: true
  validates :image, presence: true

  def self.search(search)
    return Design.all unless search
    Design.where(['title LIKE(?)', "%#{search}%"])
  end




end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor(
    :title, :file_name, :image,
    :id, :user_id,
    :tag_name
   )

   with_options presence: true do
    validates :title
    validates :file_name
    validates :image
  end


  ActiveRecord::Base.transaction do

    def save
      design = Design.create!(title: title, file_name: file_name, image: image, user_id: user_id)
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save!
      PostTagRelation.create!(design_id: design.id, tag_id: tag.id)
    end

    return true

    rescue false
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :design
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :designs, through: :post_tag_relations
  validates :tag_name,  uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true

  has_many :designs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :encrypted_password, :name])
  end



end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!, only:[:edit, :new, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  def index
    @designs = Design.includes(:user).order("created_at DESC")
    @designs = params[:tag_id].present? ? Tag.find(params[:tag_id]).designs : Design.all.order("created_at DESC")
  end

  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new(design_params)
    
    if @post_form.save
      redirect_to root_path
      else
        render :new
    end
  end

  def show
   
  end

  def destroy
    design = Design.find(params[:id])
    if design.destroy
      redirect_to root_path
    end
  end

  def update
    design = Design.find(params[:id])
    design.update(design_params)
  end

  def edit
    unless user_signed_in? && current_user.id == @design.user_id
      redirect_to action: :index
    end
  end

  def search
    @designs = Design.search(params[:post][:search]).order("created_at DESC")
  end



  private

  def design_params
    params.require(:post_form).permit(:title, :file_name, :tag_name, :image).merge(user_id: current_user.id)
  end

  def set_design
    @design = Design.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  user = User.find(params[:id])
  @name = user.name
  @designs = user.designs
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_design.html.erb
<div class="card">
    <%= link_to image_tag( design.image, class: :card__img ), design_path(design.id), method: :get %>
      <div class="card__body">
      <% if design.image.attached? %> 
        <% link_to design.title, design_path(design.id), method: :get, class: :card__title %>
        <p class="card__summary">
          <%= design.title %>
        </p>
      <% end %>
      </div>
</div>

app/views/designs/_form.html.erb
<%= form_with model: @post_form, url: designs_path, method: :post, scope: :post_form, local: true do |f| %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"design_title" %>
  </div>

  <div class="field">
    <%= f.label :file_name, "ファイルの場所" %><br />
    <%= f.text_area :file_name, class: :form__text, id:"design_file_name" %>
  </div>

  <div class="field">
    <%= f.label :image, "デザイン画像" %><br />
    <%= f.file_field :image, id:"design_image" %>
  </div>

 <div class="tag-field">
    <%= f.text_field :tag_name, placeholder: 'タグ' %>
  </div>

<div class="tag_ex"><p>※タグ例</p>
 <span class="copy_btn" >ポスター</span>
 <span class="copy_btn" >チラシ</span>
 <span class="copy_btn" >ポップ</span>
 <span class="copy_btn" >看板</span>
 <span class="copy_btn" >メニュー表</span>
 <span class="copy_btn" >マップ</span>
 <span class="copy_btn" >ご案内</span>
 <span class="copy_btn" >季節もの</span>
 </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: "form", locals: { design: @design } %>
    </div>
  </div>
</div>

app/views/designs/index.html.erb
<main class="main">
  <div class="inner">

    <%= form_with(url: search_designs_path, local:true, scope: :post, class:"search-form") do |form| %>
      <%= form.text_field :search, placeholder:"検索する", class:"search-input " %>
      <%= form.submit "検索",class: "search-btn" %>
    <% end %>

    <%= form_tag designs_path, method: :get do %>
      <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]), {prompt: 'タグで絞り込み検索',class: "tag-search",onchange: 'submit(this.form);'}%>
    <% end %>

    <div class="card__wrapper">
      <%= render partial: 'design', collection: @designs  %>
    </div>
  </div>
</main>

app/views/designs/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規デザイン登録</h2>
        <%= render partial: "designs/form", locals:{url: designs_new_path, method: :post} %>
    </div>
  </div>
</div>

app/views/designs/search.html.erb
<main class="main">
  <div class="inner">

    <%= form_with(url: search_designs_path, local: true, scope: :post, class: "search-form") do |form| %>
      <%= form.text_field :search, placeholder: "検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>

    <%= form_tag designs_path, method: :get do %>
      <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]), {prompt: 'タグで絞り込み検索',class: "tag-search",onchange: 'submit(this.form);'}%>
    <% end %>

    <div class="card__wrapper">
      <% @designs.each do |design| %>
        <%= render 'designs/design', design: design %>
      <% end %>
    </div>
  </div>
</main>

app/views/designs/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @design.title %>
      </p>
      <% if user_signed_in? && current_user.id == @design.user_id %>
      <div class="prototype__detail"><br>
          <p class="detail__title">ファイル場所</p>
          <p class="detail__message">
            <%= @design.file_name %>
          </p>
        </div>
        <div class="prototype__manage">
          <%#= link_to "編集する", edit_design_path(@design), method: :get, class: :prototype__btn %>
          <%= link_to "削除する", design_path, method: :delete, class: :prototype__btn %>
        </div>
      <% end %>

      <span class="tag_style">#<%= @design.tags.first&.tag_name %></span>

      <div class="prototype__image">
        <%= image_tag @design.image %>
      </div>
      <div class="prototype__body">
        
        <!--<div class="prototype__detail">
          <a class="mail_btn" href="mailto:it@abest.xsrv.jp?subject=製作依頼&amp;body=以下をご記入ください。%0d%0a*********************%0d%0a内容%0d%0aサイズ%0d%0a納期%0d%0a参考ファイル名 <%= @design.title %>">
          ご依頼はこちら</a>
        </div>-->
      </div>

    </div>
  </div>
</main>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- ↓クリップボード操作のために使用するjsを読み込む　( https://clipboardjs.com/ ) -->
<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.13/clipboard.min.js"></script>
 
<script>
var clipboard = new Clipboard('.copy_btn');   
 
$(function(){
    $('.copy_btn').click(function(){
        $(this).addClass('copied');   
        $(this).text('コピーしました');    
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>abest_design</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Proto", new_design_path, method: :get, class: :nav__btn %>
            </div>

          <% else %>
            <div class="nav__right">
              <%= link_to "管理者ログイン", new_user_session_path, method: :get, class: :nav__btn %>
              <%# link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>

        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Abest Hotels All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @name %>さんの情報
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @design %>
      </h2>
      <div class="user__card">
       <%= render partial: 'designs/design', collection: @design %>
      </div>
    </div>
  </div>
</div>